# name: 'Make Stack from image'
# description: 'Makes a docker-compose file by passing an image name and arguments'
# inputs:
#   image:
#     description: 'Image to use'
#     required: true
#   deployUrl:
#     description: 'Traefik host url'
#     required: true
#   port:
#     description: 'Port'
#     required: false
# outputs:
#   dockerComposeString:
#     description: 'Docker-compose file as a string'
# runs:
#   using: 'node16'
#   main: 'index.js'

name: 'Stack Deploy'
description: 'Deploys a stack'
author: 'Ludeku'
branding:
  icon: arrow-up-circle
  color: red
  stack:
    required: true
    description: 'Name of the stack you want deployed, can be new or existing. If existing, stack will be updated'
  image:
    required: true
    description: 'Name of the image'
  deployUrl:
    required: true
    description: 'Deploy url'
runs:
  using: 'node16'
  main: 'index.js'