name: 'Make Stack from image'
description: 'Makes a docker-compose file by passing an image name and arguments'
inputs:
  image:
    description: 'Image to use'
    required: true
  deployUrl:
    description: 'Traefik host url'
    required: true
  environment:
    description: 'List of environment variables'
    required: false
outputs:
  dockerComposeString:
    description: 'Docker-compose file as a string'
runs:
  using: 'node16'
  main: 'index.js'
