name: 'Deploy Stack'
description: 'Deploy service to ludeku.net'
author: 'Ludeku'
branding:
  icon: arrow-up-circle
  color: red
inputs:
  apiKey:
    required: true
    description: 'API Key'
  stack:
    required: true
    description: 'Name of the stack you want to deploy, can be new or existing. If existing, the stack will be updated'
  image:
    required: true
    description: 'Docker image'
  deployUrl:
    required: true
    description: 'Deploy url'
runs:
  using: 'node16'
  main: 'index.js'
