on: [push]

jobs:
  make_docker_compose_job:
    runs-on: ubuntu-latest
    name: A job to maka a docker-compose file
    steps:
    - name: Create docker-compose
      id: create-docker-compose
      uses: Ludeku/make-docker-compose-from-image@v1
      with:
        image: hello-world
        labels: |
          traefik.enable: 'true'
          traefik.docker.network: traefik-public
          traefik.http.routers.app.rule: Host(`myApp.domain.com`)
        env: |
          var1=var1
          var2=var2
        overlayNetworks:
          net
        externalNetworks:
          traefik-public

