on: [push]

jobs:
  make_docker_compose_job:
    runs-on: ubuntu-latest
    name: A job to maka a docker-compose file
    steps:
    - name: Create docker-compose
      id: create-docker-compose
      uses: Ludeku/make-docker-compose-from-image@v1.03
      with:
        image: hello-world
        deployUrl: 'test.ludeku.net'
        environment: |
          var1: var1
          var2: var2