on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy service as a stack
    steps:
    - name: Deploy stack
      uses: Ludeku/deploy@v1
      with:
        stack: 'hello-world'
        image: hello-world
        apiKey: ${{secrets.API_KEY}}
        deployUrl: 'hello-world.ludeku.net'
